# AUTO-GENERATED by scripts/build-powershell.ps1; edit src/windows instead.
param(
  [Parameter(Mandatory = $true)]
  [ValidateSet("client", "join", "status")]
  [string]$Command,

  [string]$Peer,
  [string]$Token,
  [int]$IperfPort = 5201,
  [ValidateSet("retrans", "throughput", "startup")]
  [string]$Objective = "retrans",
  [int]$TargetRetr = 0,
  [int]$Rounds = 5,
  [ValidateSet("download", "upload")]
  [string]$Direction = "download",
  [switch]$Yes,
  [switch]$Json,
  [switch]$NonInteractive,
  [switch]$NoColor
)

$ErrorActionPreference = "Stop"
$AppVersion = "0.3.0"
$RepoUrl = "https://github.com/10000ge10000/TCP-optimization"
$ToolRoot = Join-Path $env:LOCALAPPDATA "TCP-optimization"
$IperfCacheDir = Join-Path $ToolRoot "iperf3"
$DefaultAiGatewayUrl = "https://tcp-optimization-ai-gateway.yiwan-share.workers.dev/v1"
$DefaultAiModel = "gpt-5.5"
$AiModelCandidates = @("gpt-5.5")
$ExitSuccess = 0
$ExitArguments = 2
$ExitDependency = 3
$ExitNetwork = 4
$ExitAuthentication = 5
$ExitBenchmark = 6
$ExitAi = 8
$IperfPackage = [pscustomobject]@{
  Version = "3.18"
  Asset = "iperf-3.18-win64.zip"
  Url = "https://github.com/ar51an/iperf3-win-builds/releases/download/3.18/iperf-3.18-win64.zip"
  # 固定 GitHub Release 资产的 SHA256；升级版本时必须重新审查 ZIP 内容并更新。
  Sha256 = "8bb24166d660051ccd8946d4a8d11fca8f4987e2d83fb0300105cadb570774a9"
}
$script:UseColor = -not ($NoColor -or $env:NO_COLOR)
$script:IsNonInteractive = [bool]($NonInteractive -or -not [Environment]::UserInteractive)
if ($PSVersionTable.PSVersion.Major -ge 7 -and -not $script:UseColor) { $PSStyle.OutputRendering = "PlainText" }

# 显示宽度感知的 padding：中文字符占 2 列，ASCII 占 1 列

function Format-Pad {
  param([string]$Text, [int]$Width)
  $displayWidth = 0
  foreach ($ch in $Text.ToCharArray()) {
    $code = [int]$ch
    if ($code -ge 0x1100 -and ($code -le 0x115F -or ($code -ge 0x2E80 -and $code -le 0xA4CF) -or ($code -ge 0xAC00 -and $code -le 0xD7A3) -or ($code -ge 0xF900 -and $code -le 0xFAFF) -or ($code -ge 0xFE30 -and $code -le 0xFE4F) -or ($code -ge 0xFF00 -and $code -le 0xFF60) -or ($code -ge 0xFFE0 -and $code -le 0xFFE6))) {
      $displayWidth += 2
    } else {
      $displayWidth += 1
    }
  }
  $pad = $Width - $displayWidth
  if ($pad -gt 0) {
    return $Text + (" " * $pad)
  }
  return $Text
}

function Write-Host {
  param(
    [Parameter(Position = 0, ValueFromRemainingArguments = $true)][object[]]$Object,
    [ConsoleColor]$ForegroundColor,
    [switch]$NoNewline
  )
  $parameters = @{ Object = $Object; NoNewline = $NoNewline }
  if ($script:UseColor -and $PSBoundParameters.ContainsKey("ForegroundColor")) { $parameters.ForegroundColor = $ForegroundColor }
  Microsoft.PowerShell.Utility\Write-Host @parameters
}

function Write-Rule {
  Write-Host ("━" * 58) -ForegroundColor Cyan
}

function Write-Header {
  param([string]$Title)
  if (-not $script:IsNonInteractive) { Clear-Host }
  Write-Host ""
  Write-Host "  $Title" -ForegroundColor Cyan
  Write-Rule
}

function Write-KeyValue {
  param([string]$Label, [string]$Value)
  $padded = Format-Pad -Text $Label -Width 12
  $Value = Format-DisplayText -Text $Value
  Write-Host "  $padded  $Value"
}

function Write-PanelRule {
  Write-Host ("─" * 58) -ForegroundColor DarkGray
}

function Write-PanelRow {
  param([string]$Label, [string]$Value)
  $padded = Format-Pad -Text $Label -Width 12
  $Value = Format-DisplayText -Text $Value
  Write-Host "  $padded  $Value"
}

function Write-Section {
  param([string]$Title)
  Write-Host "  ▎ $Title" -ForegroundColor Cyan
}

function Write-Note {
  param([string]$Label, [string]$Text)
  $padded = Format-Pad -Text $Label -Width 12
  $Text = Format-DisplayText -Text $Text
  Write-Host "  $padded  $Text" -ForegroundColor DarkGray
}

function Write-Subtitle {
  param([string]$Text)
  Write-Host "  $Text" -ForegroundColor DarkGray
}

function Write-ModeCard {
  param([string]$Number, [string]$Title, [string]$Description, [string]$Target, [string]$Color = "Cyan")
  $padded = Format-Pad -Text $Title -Width 10
  Write-Host "  [$Number] " -NoNewline -ForegroundColor $Color
  Write-Host $padded -NoNewline -ForegroundColor White
  Write-Host "  $Description"
  Write-Host ("           目标：{0}" -f $Target) -ForegroundColor DarkGray
}

function Write-MetricLine {
  param([string]$Label, [string]$Value, [string]$Color = "Cyan")
  $padded = Format-Pad -Text $Label -Width 10
  Write-Host "  $padded  " -NoNewline
  Write-Host $Value -ForegroundColor $Color
}

function Write-MenuGroup {
  param([string]$Text)
  Write-Host "  $Text" -ForegroundColor Cyan
}

function Write-MenuItem {
  param([string]$Number, [string]$Title, [string]$Description, [string]$Color = "Cyan")
  $padded = Format-Pad -Text $Title -Width 16
  Write-Host "  [$Number] " -NoNewline -ForegroundColor $Color
  Write-Host $padded -NoNewline -ForegroundColor White
  Write-Host "  $Description" -ForegroundColor DarkGray
}

function Test-BackChoice {
  param([string]$Value)
  return $Value -in @("0", "q", "Q", "b", "B")
}

function Write-BackMenuItem {
  Write-MenuItem "0" "返回主菜单" "不执行本页操作" "DarkGray"
}

function Repair-DisplayText {
  param([string]$Text)
  if (-not $Text) { return "" }
  if ($Text -match "[ÃÂäåæçèé]") {
    try {
      return [System.Text.Encoding]::UTF8.GetString([System.Text.Encoding]::GetEncoding(28591).GetBytes($Text))
    } catch {
      return $Text
    }
  }
  return $Text
}

function Format-DisplayText {
  param([string]$Text, [int]$MaxWidth = 58)
  if (-not $Text) { return "" }
  try {
    if ($Host.UI.RawUI.WindowSize.Width -ge 90) { return $Text }
  } catch {
    return $Text
  }
  if ($Text.Length -le $MaxWidth) { return $Text }
  return $Text.Substring(0, [Math]::Max(0, $MaxWidth - 3)) + "..."
}

function Get-PercentDelta {
  param([Nullable[Double]]$Before, [Nullable[Double]]$After)
  if ($null -eq $Before -or $null -eq $After) { return "未检测" }
  if ($Before -le 0) { return "建立基线" }
  $delta = (($After - $Before) * 100.0) / $Before
  if ($delta -gt 0) { return ("+{0:N0}%" -f $delta) }
  return ("{0:N0}%" -f $delta)
}

function Get-TrendLabel {
  param([Nullable[Int64]]$Current, [Nullable[Int64]]$Previous)
  if ($null -eq $Current) { return "未检测" }
  if ($null -eq $Previous) { return "建立基线" }
  if ($Current -lt $Previous) { return "重传下降" }
  if ($Current -gt $Previous) { return "重传上升" }
  return "保持稳定"
}

function Get-NextActionLabel {
  param([string]$ObjectiveValue, [Nullable[Int64]]$Retransmits, [Int64]$TargetRetransmits)
  if ($null -eq $Retransmits) { return "未检测到重传指标，不能据此判断。" }
  switch ($ObjectiveValue) {
    "throughput" {
      if ($Retransmits -le $TargetRetransmits) { return "重传可接受，继续观察稳定吞吐。" }
      return "重传偏高，建议先降低排队压力。"
    }
    "startup" { return "关注首秒速度，判断短连接起速表现。" }
    default {
      if ($Retransmits -le $TargetRetransmits) { return "已达到目标，保持当前建议。" }
      return "继续压低重传，优先减少排队。"
    }
  }
}

function Install-Iperf3 {
  if (-not $IperfPackage.Sha256 -or $IperfPackage.Sha256 -notmatch '^[0-9a-fA-F]{64}$') {
    throw "自动安装已安全停止：iperf3 $($IperfPackage.Version) 的发布 SHA256 尚未由维护者确认。请手动安装可信版本并加入 PATH。"
  }
  New-Item -ItemType Directory -Force -Path $IperfCacheDir | Out-Null
  $staging = Join-Path $IperfCacheDir ("staging-" + [guid]::NewGuid().ToString("N"))
  $zipPath = Join-Path $staging $IperfPackage.Asset
  $extractPath = Join-Path $staging "extract"
  try {
    New-Item -ItemType Directory -Force -Path $extractPath | Out-Null
    try {
      Invoke-WebRequest -Uri $IperfPackage.Url -OutFile $zipPath -UseBasicParsing -TimeoutSec 60
    } catch {
      $message = $_.Exception.Message
      if ($message -match '407|proxy') { throw "iperf3 下载失败：代理认证失败（HTTP 407）。请检查系统代理。" }
      if ($message -match '403|429') { throw "iperf3 下载被上游拒绝或限流。请稍后重试或手动安装固定版本 $($IperfPackage.Version)。" }
      throw "iperf3 下载失败：$message"
    }
    $actualHash = (Get-FileHash -LiteralPath $zipPath -Algorithm SHA256).Hash
    if ($actualHash -ne $IperfPackage.Sha256) { throw "iperf3 SHA256 校验失败，安装已取消。" }
    Expand-SafeZip -ZipPath $zipPath -DestinationPath $extractPath
    $executables = @(Get-ChildItem -LiteralPath $extractPath -Recurse -File -Filter iperf3.exe)
    if ($executables.Count -ne 1) { throw "压缩包必须且只能包含一个 iperf3.exe。" }
    $versionText = (& $executables[0].FullName --version 2>&1 | Out-String)
    if ($LASTEXITCODE -ne 0 -or $versionText -notmatch [regex]::Escape($IperfPackage.Version)) { throw "iperf3 版本验证失败。" }
    $target = Join-Path $IperfCacheDir $IperfPackage.Version
    $oldTarget = $null
    if (Test-Path -LiteralPath $target) {
      $oldTarget = Join-Path $IperfCacheDir ("previous-" + [guid]::NewGuid().ToString("N"))
      Move-Item -LiteralPath $target -Destination $oldTarget
    }
    try {
      Move-Item -LiteralPath $extractPath -Destination $target
      [IO.File]::WriteAllText((Join-Path $target ".tcp-tune-sha256"), $IperfPackage.Sha256, [Text.UTF8Encoding]::new($false))
    } catch {
      if (Test-Path -LiteralPath $target) { Remove-Item -LiteralPath $target -Recurse -Force }
      if ($oldTarget -and (Test-Path -LiteralPath $oldTarget)) { Move-Item -LiteralPath $oldTarget -Destination $target }
      throw
    }
    if ($oldTarget -and (Test-Path -LiteralPath $oldTarget)) { Remove-Item -LiteralPath $oldTarget -Recurse -Force }
    $exe = Get-ChildItem -LiteralPath $target -Recurse -File -Filter iperf3.exe | Select-Object -First 1
    $env:PATH = "$($exe.Directory.FullName);$env:PATH"
    Write-Host "iperf3 已安装到用户缓存：$($exe.FullName)" -ForegroundColor Green
  } finally {
    if (Test-Path -LiteralPath $staging) { Remove-Item -LiteralPath $staging -Recurse -Force }
  }
}

function Expand-SafeZip {
  param([Parameter(Mandatory)][string]$ZipPath, [Parameter(Mandatory)][string]$DestinationPath)
  Add-Type -AssemblyName System.IO.Compression.FileSystem
  $root = [IO.Path]::GetFullPath($DestinationPath).TrimEnd([IO.Path]::DirectorySeparatorChar) + [IO.Path]::DirectorySeparatorChar
  $archive = [IO.Compression.ZipFile]::OpenRead($ZipPath)
  try {
    foreach ($entry in $archive.Entries) {
      if ([string]::IsNullOrWhiteSpace($entry.FullName)) { continue }
      $unixType = (($entry.ExternalAttributes -shr 16) -band 0xF000)
      $dosAttributes = ($entry.ExternalAttributes -band 0xFFFF)
      if ($unixType -eq 0xA000 -or ($dosAttributes -band 0x400)) { throw "压缩包包含链接或重解析点。" }
      if ($entry.FullName.IndexOf([char]0) -ge 0 -or $entry.FullName -match '^[\\/]|^[A-Za-z]:|(^|[\\/])\.\.([\\/]|$)') {
        throw "压缩包包含不安全路径：$($entry.FullName)"
      }
      $target = [IO.Path]::GetFullPath((Join-Path $DestinationPath $entry.FullName))
      if (-not $target.StartsWith($root, [StringComparison]::OrdinalIgnoreCase)) { throw "压缩包路径越界。" }
    }
  } finally { $archive.Dispose() }
  Expand-Archive -LiteralPath $ZipPath -DestinationPath $DestinationPath -Force
}

function Ensure-Command {
  param([string]$Name)
  if ($Name -eq "iperf3") {
    $cached = Get-CachedIperf3
    if ($cached) {
      $env:PATH = "$((Split-Path -Parent $cached));$env:PATH"
    }
  }
  if (-not (Get-Command $Name -ErrorAction SilentlyContinue)) {
    if ($Name -eq "iperf3" -and $Yes) {
      Install-Iperf3
    }
  }
  if (-not (Get-Command $Name -ErrorAction SilentlyContinue)) {
    throw "缺少命令：$Name。请安装 Windows 版 iperf3 并加入 PATH。"
  }
}

function Get-PresetProfiles {
  return @(
    [pscustomobject]@{ Index = "1"; Name = "近距轻载"; Rtt = "RTT < 30ms"; Rmem = "64MiB"; Wmem = "32MiB"; Comment = "低延迟链路，优先控制发送队列和重传。" },
    [pscustomobject]@{ Index = "2"; Name = "近距高速"; Rtt = "RTT 30~70ms"; Rmem = "64MiB"; Wmem = "64MiB"; Comment = "同区域或精品线路，适合较高下行和稳定短中距链路。" },
    [pscustomobject]@{ Index = "3"; Name = "中距均衡"; Rtt = "RTT 70~130ms"; Rmem = "约 85MiB"; Wmem = "约 41MiB"; Comment = "跨境中等延迟，接收缓冲略大于发送缓冲。" },
    [pscustomobject]@{ Index = "4"; Name = "长距增强"; Rtt = "RTT 130~190ms"; Rmem = "约 100MiB"; Wmem = "约 48MiB"; Comment = "亚太/跨海高带宽链路，适合较大 BDP。" },
    [pscustomobject]@{ Index = "5"; Name = "远距大带宽"; Rtt = "RTT > 190ms"; Rmem = "约 178MiB"; Wmem = "约 85MiB"; Comment = "欧美等高延迟链路，缓冲更大，低内存设备需谨慎。" }
  )
}

function Get-RttMilliseconds {
  param([string]$HostName)
  try {
    $samples = Test-Connection -ComputerName $HostName -Count 3 -ErrorAction Stop
    $values = foreach ($sample in $samples) {
      if ($null -ne $sample.ResponseTime) { [double]$sample.ResponseTime }
      elseif ($null -ne $sample.Latency) { [double]$sample.Latency }
    }
    if ($values) { return [int](($values | Measure-Object -Average).Average) }
  } catch {
  }
  return 0
}

function Select-PresetByProbe {
  param([int]$RttMs, [Nullable[Int64]]$Retransmits, [double]$DownloadBitsPerSecond)
  if ($RttMs -lt 30) { $index = 1 }
  elseif ($RttMs -lt 70) { $index = 2 }
  elseif ($RttMs -lt 130) { $index = 3 }
  elseif ($RttMs -lt 190) { $index = 4 }
  else { $index = 5 }
  if ($null -ne $Retransmits -and $Retransmits -gt 500 -and $index -gt 1) { $index-- }
  if ($DownloadBitsPerSecond -gt 0 -and $DownloadBitsPerSecond -lt 20000000 -and $index -gt 3) { $index = 3 }
  return (Get-PresetProfiles | Where-Object { $_.Index -eq "$index" } | Select-Object -First 1)
}

function Get-CachedIperf3 {
  if (-not $IperfPackage.Sha256 -or $IperfPackage.Sha256 -notmatch '^[0-9a-fA-F]{64}$') { return $null }
  $versionDir = Join-Path $IperfCacheDir $IperfPackage.Version
  $marker = Join-Path $versionDir ".tcp-tune-sha256"
  if (-not (Test-Path -LiteralPath $marker -PathType Leaf)) { return $null }
  if (([IO.File]::ReadAllText($marker).Trim()) -ne $IperfPackage.Sha256) { return $null }
  $executables = @(Get-ChildItem -LiteralPath $versionDir -Recurse -File -Filter iperf3.exe -ErrorAction SilentlyContinue)
  if ($executables.Count -eq 1) { return $executables[0].FullName }
  return $null
}

function Invoke-AgentPost {
  param(
    [string]$Url,
    [string]$TokenValue,
    [object]$Body
  )
  if (-not $TokenValue -or $TokenValue.Length -gt 256 -or $TokenValue -match '[\r\n]') { throw "Agent token 无效。" }
  $uri = [Uri]$Url
  if ($uri.Scheme -notin @("http", "https")) { throw "Agent URL 只允许 HTTP(S)。" }
  $headers = @{ "X-TCP-Tune-Token" = $TokenValue }
  $json = $Body | ConvertTo-Json -Depth 6
  if ([Text.Encoding]::UTF8.GetByteCount($json) -gt 32768) { throw "Agent 请求体超过 32 KiB。" }
  Invoke-RestMethod -Method Post -Uri $Url -Headers $headers -ContentType "application/json" -Body $json -TimeoutSec 30
}

function Invoke-AgentGet {
  param([string]$Url, [string]$TokenValue)
  if (-not $TokenValue -or $TokenValue.Length -gt 256 -or $TokenValue -match '[\r\n]') { throw "Agent token 无效。" }
  Invoke-RestMethod -Method Get -Uri $Url -Headers @{ "X-TCP-Tune-Token" = $TokenValue } -TimeoutSec 30
}

function Test-RemoteDefaultsAvailable {
  param([string]$PeerUrl, [string]$TokenValue)
  try {
    $data = Invoke-AgentGet -Url "$PeerUrl/defaults" -TokenValue $TokenValue
    return [bool]$data.available
  } catch {
    return $false
  }
}

function Get-DefaultsMenuTag {
  param([string]$PeerUrl, [string]$TokenValue)
  $remote = if (Test-RemoteDefaultsAvailable -PeerUrl $PeerUrl -TokenValue $TokenValue) { "服务端已记录" } else { "服务端未知" }
  return "[本机不适用 / $remote]"
}

function Get-PeerHost {
  param([string]$Url)
  $uri = Test-PeerUri -Url $Url
  return $uri.DnsSafeHost
}

function Test-PeerUri {
  param([Parameter(Mandatory)][string]$Url)
  $uri = $null
  if (-not [Uri]::TryCreate($Url, [UriKind]::Absolute, [ref]$uri)) { throw "Peer 必须是绝对 HTTP(S) URL。" }
  if ($uri.Scheme -notin @("http", "https")) { throw "Peer 只允许 http 或 https。" }
  if (-not [string]::IsNullOrEmpty($uri.UserInfo) -or $uri.Query -or $uri.Fragment) { throw "Peer 不允许用户信息、查询参数或片段。" }
  if ($uri.AbsolutePath -ne "/") { throw "Peer URL 不应包含接口路径。" }
  Test-IperfHost -HostName $uri.DnsSafeHost | Out-Null
  return $uri
}

function Test-IperfHost {
  param([Parameter(Mandatory)][string]$HostName)
  if ($HostName.Length -gt 253 -or $HostName.StartsWith("-") -or $HostName -match '[\x00-\x20/\\]') {
    throw "对端主机名不安全或超出长度限制。"
  }
  $ip = $null
  if ([Net.IPAddress]::TryParse($HostName, [ref]$ip)) { return $true }
  if ($HostName -notmatch '^(?=.{1,253}$)([A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?\.)*[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?$') {
    throw "对端主机名格式无效。"
  }
  return $true
}

function Get-LocalLanIPv4 {
  try {
    $interfaces = [Net.NetworkInformation.NetworkInterface]::GetAllNetworkInterfaces() |
      Where-Object { $_.OperationalStatus -eq [Net.NetworkInformation.OperationalStatus]::Up }
    foreach ($interface in $interfaces) {
      $properties = $interface.GetIPProperties()
      if (-not @($properties.GatewayAddresses).Count) { continue }
      $address = $properties.UnicastAddresses |
        Where-Object { $_.Address.AddressFamily -eq [Net.Sockets.AddressFamily]::InterNetwork -and $_.Address.IPAddressToString -notlike "169.254.*" } |
        Select-Object -First 1
      if ($address) { return $address.Address.IPAddressToString }
    }
  } catch {
    # Fall through to DNS-based discovery for restricted environments.
  }

  $address = [System.Net.Dns]::GetHostAddresses([System.Net.Dns]::GetHostName()) |
    Where-Object {
      $_.AddressFamily -eq [System.Net.Sockets.AddressFamily]::InterNetwork -and
      -not $_.IPAddressToString.StartsWith("127.") -and
      -not $_.IPAddressToString.StartsWith("169.254.")
    } |
    Select-Object -First 1
  if ($address) { return $address.IPAddressToString }
  return "未识别"
}

function Get-LocalLanIPv6 {
  try {
    foreach ($interface in [Net.NetworkInformation.NetworkInterface]::GetAllNetworkInterfaces()) {
      if ($interface.OperationalStatus -ne [Net.NetworkInformation.OperationalStatus]::Up) { continue }
      $address = $interface.GetIPProperties().UnicastAddresses |
        Where-Object {
          $_.Address.AddressFamily -eq [Net.Sockets.AddressFamily]::InterNetworkV6 -and
          -not $_.Address.IsIPv6LinkLocal -and -not $_.Address.IsIPv6Multicast -and $_.Address.IPAddressToString -ne "::1"
        } | Select-Object -First 1
      if ($address) { return $address.Address.IPAddressToString }
    }
  } catch {
    # Return an explicit unknown state below.
  }
  return "未识别"
}

function Test-IPv6Literal {
  param([string]$HostName)
  $ip = $null
  if ([System.Net.IPAddress]::TryParse($HostName, [ref]$ip)) {
    return $ip.AddressFamily -eq [System.Net.Sockets.AddressFamily]::InterNetworkV6
  }
  return $false
}

function Get-LocalBindAddress {
  param([string]$HostName)
  if (Test-IPv6Literal -HostName $HostName) {
    return Get-LocalLanIPv6
  }
  return Get-LocalLanIPv4
}

function Get-ObjectiveLabel {
  param([string]$Value)
  switch ($Value) {
    "throughput" { return "吞吐优先" }
    "startup" { return "快速起速" }
    default { return "重传优先" }
  }
}

function Get-DirectionLabel {
  param([string]$Value)
  if ($Value -eq "upload") { return "上传（本机 → 服务端）" }
  return "下载（服务端 → 本机）"
}

function Format-Rate {
  param([Nullable[Double]]$BitsPerSecond)
  if ($null -eq $BitsPerSecond) { return "未检测" }
  if ($BitsPerSecond -ge 1000000000) {
    return ("{0:N2} Gbps" -f ($BitsPerSecond / 1000000000))
  }
  return ("{0:N1} Mbps" -f ($BitsPerSecond / 1000000))
}

function Test-IperfBindCompatible {
  param([string]$HostName, [string]$LocalAddress)
  if (-not $LocalAddress -or $LocalAddress -eq "未识别" -or $HostName -in @("127.0.0.1", "localhost", $LocalAddress)) {
    return $false
  }
  $localIp = $null
  if (-not [Net.IPAddress]::TryParse($LocalAddress, [ref]$localIp)) { return $false }
  $targetIp = $null
  if ([Net.IPAddress]::TryParse($HostName, [ref]$targetIp)) {
    return $localIp.AddressFamily -eq $targetIp.AddressFamily
  }
  # 已通过 Test-IperfHost 校验的 hostname 保持既有绑定行为，地址族由系统解析决定。
  return $true
}

function Run-Iperf {
  param(
    [string]$HostName,
    [int]$Port,
    [string]$LocalAddress,
    [switch]$Reverse
  )
  Test-IperfHost -HostName $HostName | Out-Null
  if ($Port -lt 1 -or $Port -gt 65535) { throw "iperf3 端口必须在 1 到 65535 之间。" }
  $arguments = @("-c", $HostName, "-p", "$Port", "-t", "15", "-i", "1", "-J")
  if (Test-IperfBindCompatible -HostName $HostName -LocalAddress $LocalAddress) {
    $arguments += @("-B", $LocalAddress)
  }
  if ($Reverse) { $arguments += "-R" }

  $raw = Invoke-IperfProcess -Arguments $arguments -TimeoutSeconds 35
  try { return ($raw | ConvertFrom-Json -ErrorAction Stop) } catch { throw "iperf3 返回了无效 JSON。" }
}

function Add-NullableInt64 {
  param([Nullable[Int64]]$Left, [Nullable[Int64]]$Right)
  if ($null -eq $Left -or $null -eq $Right) { return $null }
  return [Int64]($Left + $Right)
}

function Max-NullableDouble {
  param([Nullable[Double]]$Left, [Nullable[Double]]$Right)
  if ($null -eq $Left) { return $Right }
  if ($null -eq $Right) { return $Left }
  return [Math]::Max($Left.Value, $Right.Value)
}

function Invoke-IperfProcess {
  param([string[]]$Arguments, [int]$TimeoutSeconds)
  if ($TimeoutSeconds -lt 1 -or $TimeoutSeconds -gt 300) { throw "iperf3 超时时间无效。" }
  $command = Get-Command iperf3 -ErrorAction Stop
  $psi = [Diagnostics.ProcessStartInfo]::new()
  $psi.FileName = $command.Source
  $psi.UseShellExecute = $false
  $psi.CreateNoWindow = $true
  $psi.RedirectStandardOutput = $true
  $psi.RedirectStandardError = $true
  $psi.Arguments = (($Arguments | ForEach-Object {
    if ($_ -match '[\x00\r\n"]') { throw "iperf3 参数包含非法字符。" }
    '"' + $_ + '"'
  }) -join ' ')
  $process = [Diagnostics.Process]::new()
  $process.StartInfo = $psi
  try {
    if (-not $process.Start()) { throw "无法启动 iperf3。" }
    $stdoutTask = $process.StandardOutput.ReadToEndAsync()
    $stderrTask = $process.StandardError.ReadToEndAsync()
    if (-not $process.WaitForExit($TimeoutSeconds * 1000)) {
      try { $process.Kill() } catch {}
      throw "iperf3 测试超时，进程已停止。"
    }
    $stdout = $stdoutTask.GetAwaiter().GetResult()
    $stderr = $stderrTask.GetAwaiter().GetResult()
    if ($process.ExitCode -ne 0) {
      $detail = if ($stderr) { $stderr.Trim() } else { "exit $($process.ExitCode)" }
      throw "iperf3 测试失败：$detail"
    }
    return $stdout
  } finally { $process.Dispose() }
}

function Invoke-Iperf3Speedtest {
  param([string]$HostName, [int]$Port)

  Write-Header "iperf3 速度测试"
  Write-Subtitle "简单测速，不修改任何参数"
  Write-Host ""
  Write-Section "测试参数"
  Write-PanelRow "对端地址" $HostName
  Write-PanelRow "端口" $Port
  Write-PanelRow "测试方向" "下载（服务端 → 本机）"
  Write-PanelRow "测试时长" "10秒"
  if (Test-IPv6Literal -HostName $HostName) {
    Write-Note "IPv6" "检测到 IPv6 地址，使用 IPv6 测速"
  }
  Write-Host ""
  Write-Note "状态" "正在测速..."
  Ensure-Command -Name "iperf3"
  Write-Host ""
  $arguments = @("-c", $HostName, "-p", "$Port", "-R", "-t", "10")
  & iperf3 @arguments
  if ($LASTEXITCODE -eq 0) {
    Write-Host ""
    Write-Section "测速完成"
  } else {
    Write-Host ""
    Write-Host "测速失败，请检查对端 iperf3 服务是否运行。" -ForegroundColor Yellow
  }
}

function Get-IperfMetrics {
  param([object]$Result)
  if (-not $Result -or -not $Result.end) {
    throw "iperf3 测试失败：未获得有效结果。"
  }
  $summary = $Result.end.sum_received
  if (-not $summary) { $summary = $Result.end.sum_sent }
  if (-not $summary) {
    throw "iperf3 测试失败：缺少传输汇总。"
  }

  [Nullable[Int64]]$retransmits = $null
  if ($Result.end.sum_sent -and $null -ne $Result.end.sum_sent.retransmits) {
    $retransmits = [int64]$Result.end.sum_sent.retransmits
  }
  $bitsPerSecond = 0.0
  if ($summary -and $summary.bits_per_second) {
    $bitsPerSecond = [double]$summary.bits_per_second
  }
  if ($bitsPerSecond -le 0) {
    throw "iperf3 测试失败：速率为 0，请检查对端端口和链路。"
  }
  [Nullable[Double]]$firstSecondBits = $null
  if ($Result.intervals -and $Result.intervals.Count -gt 0 -and $Result.intervals[0].sum -and $null -ne $Result.intervals[0].sum.bits_per_second) {
    $firstSecondBits = [double]$Result.intervals[0].sum.bits_per_second
  }

  return [pscustomobject]@{
    BitsPerSecond = $bitsPerSecond
    FirstSecondBitsPerSecond = $firstSecondBits
    Retransmits = $retransmits
  }
}

function Invoke-AIChat {
  param([string]$Model, [string]$Prompt, [int]$MaxTokens = 512)
  if (-not $Model -or $Model.Length -gt 128 -or $Model -notmatch '^[A-Za-z0-9._:/-]+$') { throw "AI 模型名称无效。" }
  if (-not $Prompt -or $Prompt.Length -gt 32000) { throw "AI 请求内容为空或超过 32000 字符。" }
  if ($MaxTokens -lt 1 -or $MaxTokens -gt 1024) { throw "AI max_tokens 必须在 1 到 1024 之间。" }
  $baseUrl = $env:TCP_TUNE_AI_GATEWAY_URL
  if (-not $baseUrl) { $baseUrl = $DefaultAiGatewayUrl }
  $baseUrl = $baseUrl.TrimEnd("/")
  $headers = @{
    "Content-Type" = "application/json"
    "Accept" = "application/json"
    "User-Agent" = "TCP-optimization/Windows"
  }
  $baseUri = $null
  if (-not [Uri]::TryCreate($baseUrl, [UriKind]::Absolute, [ref]$baseUri) -or $baseUri.Scheme -ne "https") { throw "AI 网关必须是 HTTPS URL。" }
  $nvidiaBase = if ($env:NVIDIA_BASE_URL) { $env:NVIDIA_BASE_URL.TrimEnd("/") } else { "https://integrate.api.nvidia.com/v1" }
  $nvidiaUri = [Uri]$nvidiaBase
  $isNvidiaDirect = $baseUri.Host -eq $nvidiaUri.Host -and $baseUri.AbsolutePath.TrimEnd("/") -eq $nvidiaUri.AbsolutePath.TrimEnd("/")
  if ($isNvidiaDirect -and $env:NVIDIA_API_KEY) {
    $headers["Authorization"] = "Bearer $env:NVIDIA_API_KEY"
  } elseif ($env:TCP_TUNE_AI_GATEWAY_TOKEN) {
    $headers["Authorization"] = "Bearer $env:TCP_TUNE_AI_GATEWAY_TOKEN"
  }
  $body = @{
    model = $Model
    messages = @(@{ role = "user"; content = $Prompt })
    temperature = 0
    max_tokens = $MaxTokens
  } | ConvertTo-Json -Depth 8
  $timeout = 90
  if ($env:TCP_TUNE_AI_TIMEOUT) {
    $parsedTimeout = 0
    if (-not [int]::TryParse($env:TCP_TUNE_AI_TIMEOUT, [ref]$parsedTimeout) -or $parsedTimeout -lt 5 -or $parsedTimeout -gt 180) { throw "TCP_TUNE_AI_TIMEOUT 必须在 5 到 180 秒之间。" }
    $timeout = $parsedTimeout
  }
  for ($attempt = 1; $attempt -le 3; $attempt++) {
    try {
      $response = Invoke-RestMethod -Method Post -Uri "$baseUrl/chat/completions" -Headers $headers -Body $body -TimeoutSec $timeout
      $content = $response.choices[0].message.content
      if ($content -is [array]) {
        $content = ($content | ForEach-Object {
          if ($_.text) { $_.text } elseif ($_.content) { $_.content } else { "" }
        }) -join ""
      }
      if ($content) { return [string]$content }
    } catch {
      if ($attempt -eq 3) { throw }
      Start-Sleep -Seconds 1
    }
  }
  throw "AI 没有返回内容。"
}

function Format-Retransmits {
  param([Nullable[Int64]]$Retransmits)
  if ($null -eq $Retransmits) { return "未检测" }
  return ("{0:N0} 次" -f $Retransmits)
}

function Get-RetransmitsColor {
  param([Nullable[Int64]]$Retransmits)
  if ($null -eq $Retransmits) { return "DarkGray" }
  if ($Retransmits -gt 0) { return "Yellow" }
  return "Green"
}

function Test-RetransmitsAtOrBelowTarget {
  param([Nullable[Int64]]$Retransmits, [Int64]$Target)
  return ($null -ne $Retransmits -and $Retransmits -le $Target)
}

function Select-AIModel {
  if ($env:NVIDIA_MODEL -and $env:NVIDIA_MODEL -ne "auto") { return $env:NVIDIA_MODEL }
  if (-not $env:NVIDIA_MODEL) { return $DefaultAiModel }
  if ($AiModelCandidates.Count -lt 1) { throw "没有已配置的 AI 模型。" }
  # Tuning pins one configured alias for the entire session. A short latency
  # probe is not evidence that a model is accurate enough for TCP decisions.
  return [string]$AiModelCandidates[0]
}

function ConvertFrom-AIJson {
  param([string]$Text)
  if (-not $Text -or $Text.Length -gt 16000) { throw "AI 响应为空或过大。" }
  $trimmed = $Text.Trim()
  if (-not ($trimmed.StartsWith("{") -and $trimmed.EndsWith("}"))) { throw "AI 必须只返回一个 JSON 对象。" }
  try { $result = $trimmed | ConvertFrom-Json -ErrorAction Stop } catch { throw "AI 返回的 JSON 无效。" }
  $allowed = @("action", "risk", "reason", "windows_change")
  $names = @($result.PSObject.Properties.Name)
  if (@($names | Where-Object { $_ -notin $allowed }).Count -gt 0) { throw "AI JSON 包含未知字段。" }
  foreach ($required in $allowed) { if ($required -notin $names) { throw "AI JSON 缺少字段：$required" } }
  if ([string]$result.risk -notin @("low", "medium", "high")) { throw "AI risk 枚举无效。" }
  if ([string]$result.windows_change -notin @("none", "manual-only")) { throw "AI windows_change 枚举无效。" }
  if ([string]$result.action -match '[\r\n]' -or ([string]$result.action).Length -gt 256) { throw "AI action 超出限制。" }
  if ([string]$result.reason -match '[\r\n]' -or ([string]$result.reason).Length -gt 512) { throw "AI reason 超出限制。" }
  return $result
}

function New-WindowsAIEvidenceV2 {
  param(
    [ValidateSet("startup", "throughput", "retrans")][string]$Objective,
    [Parameter(Mandatory = $true)]$Upload,
    [Parameter(Mandatory = $true)]$Download,
    [Nullable[Int64]]$RttMs,
    [string]$MeasurementId
  )
  if (-not $MeasurementId) {
    $MeasurementId = "windows_{0}_{1}" -f [DateTimeOffset]::UtcNow.ToUnixTimeSeconds(), ([guid]::NewGuid().ToString("N").Substring(0, 8))
  }
  if ($MeasurementId -notmatch '^[a-z][a-z0-9_-]{0,63}$') { throw "AI measurement_id 格式无效。" }

  return [pscustomobject][ordered]@{
    schema_version = "2"
    platform = "windows"
    read_only = $true
    objective = $Objective
    measurement_id = $MeasurementId
    rtt_ms = $RttMs
    upload = [pscustomobject][ordered]@{
      throughput_bps = $Upload.BitsPerSecond
      retransmits = $Upload.Retransmits
      first_second_bps = $Upload.FirstSecondBitsPerSecond
    }
    download = [pscustomobject][ordered]@{
      throughput_bps = $Download.BitsPerSecond
      retransmits = $Download.Retransmits
      first_second_bps = $Download.FirstSecondBitsPerSecond
    }
    constraints = [pscustomobject][ordered]@{
      system_tcp_write_allowed = $false
      candidate_execution_allowed = $false
      allowed_actions = @("measure", "test_candidate", "stop_no_change", "stop_complete")
    }
  }
}

function Test-AICsvIdentifiers {
  param(
    [AllowNull()][string]$Value,
    [int]$MaximumItems,
    [string]$Pattern,
    [string]$FieldName
  )
  if ([string]::IsNullOrEmpty($Value)) { return @() }
  if ($Value.Length -gt 768 -or $Value.Trim() -ne $Value) { throw "AI $FieldName 格式无效。" }
  $items = @($Value -split ',', -1)
  if ($items.Count -gt $MaximumItems -or @($items | Where-Object { $_ -notmatch $Pattern }).Count -gt 0) {
    throw "AI $FieldName 格式无效。"
  }
  $unique = @($items | Select-Object -Unique)
  if ($unique.Count -ne $items.Count) { throw "AI $FieldName 包含重复语义。" }
  return $items
}

function ConvertFrom-AIDecisionV2 {
  param([string]$Text)
  if (-not $Text -or $Text.Length -gt 16000) { throw "AI v2 响应为空或过大。" }
  $trimmed = $Text.Trim()
  if (-not ($trimmed.StartsWith("{") -and $trimmed.EndsWith("}"))) { throw "AI v2 必须只返回一个 JSON 对象。" }

  $keyMatches = [regex]::Matches($trimmed, '(?<!\\)"(?<key>[A-Za-z_][A-Za-z0-9_]*)"\s*:')
  $wireKeys = @($keyMatches | ForEach-Object { $_.Groups["key"].Value })
  $seenWireKeys = @{}
  foreach ($wireKey in $wireKeys) {
    $semanticKey = $wireKey.ToLowerInvariant()
    if ($seenWireKeys.ContainsKey($semanticKey)) { throw "AI v2 JSON 包含重复字段。" }
    $seenWireKeys[$semanticKey] = $true
  }

  try { $result = $trimmed | ConvertFrom-Json -ErrorAction Stop } catch { throw "AI v2 返回的 JSON 无效。" }
  if ($null -eq $result -or $result -is [array] -or $result -is [string]) { throw "AI v2 响应必须是扁平对象。" }
  $allowed = @(
    "schema_version", "action", "diagnosis_class", "confidence_milli", "candidate_id",
    "measurement_id", "evidence_ids", "reason_codes", "expected_metric", "expected_direction", "stop_reason"
  )
  $names = @($result.PSObject.Properties.Name)
  if ($names.Count -ne $allowed.Count) { throw "AI v2 JSON 字段数量无效。" }
  if (@($names | Where-Object { -not ($allowed -ccontains $_) }).Count -gt 0) { throw "AI v2 JSON 包含未知字段。" }
  foreach ($required in $allowed) { if (-not ($names -ccontains $required)) { throw "AI v2 JSON 缺少字段：$required" } }

  if ($result.schema_version -isnot [string] -or $result.schema_version -cne "2") { throw "AI schema_version 必须为字符串 2。" }
  if ($result.confidence_milli -isnot [int] -and $result.confidence_milli -isnot [long]) { throw "AI confidence_milli 类型无效。" }
  if ([int64]$result.confidence_milli -lt 0 -or [int64]$result.confidence_milli -gt 1000) { throw "AI confidence_milli 超出范围。" }

  $actions = @("measure", "test_candidate", "stop_no_change", "stop_complete")
  $diagnoses = @("healthy_no_change", "path_congestion", "local_send_queue", "bdp_limited", "congestion_control_mismatch", "qdisc_pressure", "cpu_memory_limited", "pmtu_issue", "unstable_evidence", "unsupported_protocol")
  $metrics = @("throughput", "retransmits", "first_second", "rtt", "qdisc_drop", "qdisc_backlog", "none")
  $directions = @("increase", "decrease", "stable", "none")
  $stopReasons = @("none", "need_measurement", "no_safe_candidate", "objective_met", "platform_read_only", "unsupported_protocol", "budget_exhausted", "unstable_evidence")
  if ([string]$result.action -notin $actions) { throw "AI action 枚举无效。" }
  if ([string]$result.diagnosis_class -notin $diagnoses) { throw "AI diagnosis_class 枚举无效。" }
  if ([string]$result.expected_metric -notin $metrics) { throw "AI expected_metric 枚举无效。" }
  if ([string]$result.expected_direction -notin $directions) { throw "AI expected_direction 枚举无效。" }
  if ([string]$result.stop_reason -notin $stopReasons) { throw "AI stop_reason 枚举无效。" }

  foreach ($idField in @("candidate_id", "measurement_id")) {
    $idValue = $result.$idField
    if ($idValue -isnot [string] -or ($idValue.Length -gt 0 -and $idValue -notmatch '^[a-z][a-z0-9_-]{0,63}$')) {
      throw "AI $idField 格式无效。"
    }
  }
  if ($result.evidence_ids -isnot [string] -or $result.reason_codes -isnot [string]) { throw "AI evidence_ids/reason_codes 类型无效。" }
  if ([string]::IsNullOrEmpty([string]$result.evidence_ids)) { throw "AI evidence_ids 不能为空。" }
  [void](Test-AICsvIdentifiers -Value $result.evidence_ids -MaximumItems 12 -Pattern '^[a-z][a-z0-9_.]{0,63}$' -FieldName "evidence_ids")
  [void](Test-AICsvIdentifiers -Value $result.reason_codes -MaximumItems 8 -Pattern '^[a-z][a-z0-9_]{0,47}$' -FieldName "reason_codes")

  $hasCandidate = -not [string]::IsNullOrEmpty([string]$result.candidate_id)
  $hasMeasurement = -not [string]::IsNullOrEmpty([string]$result.measurement_id)
  switch ([string]$result.action) {
    "measure" {
      if ($hasCandidate -or -not $hasMeasurement) { throw "AI measure 决策语义无效。" }
    }
    "test_candidate" {
      if (-not $hasCandidate -or $hasMeasurement) { throw "AI test_candidate 决策语义无效。" }
    }
    "stop_no_change" { if ($hasCandidate -or $hasMeasurement) { throw "AI stop_no_change 决策语义无效。" } }
    "stop_complete" { if ($hasCandidate -or $hasMeasurement) { throw "AI stop_complete 决策语义无效。" } }
  }
  return $result
}

function Get-WindowsAIV2ActionLabel {
  param([string]$Action)
  switch ($Action) {
    "measure" { return "需要补充测量" }
    "test_candidate" { return "建议测试候选（Windows 只读，不执行）" }
    "stop_no_change" { return "停止且不修改" }
    "stop_complete" { return "目标已满足，结束分析" }
    default { throw "未知 AI v2 action。" }
  }
}

function Invoke-WindowsAITuning {
  param([string]$PeerUrl, [string]$TokenValue, [string]$HostName, [int]$Port, [string]$LocalAddress)
  Write-Header "AI 智能调参"
  Write-Subtitle "Windows 端会真实测速并显示 AI 建议；默认不写 Windows TCP 栈。"
  Write-Host ""
  Write-Section "AI 调参目标"
  Write-ModeCard "1" "快速起速" "适合网页、短连接、小文件。" "缩短连接初期提速时间" "Yellow"
  Write-ModeCard "2" "吞吐优先" "适合下载、备份、大文件。" "优先提高稳定传输速度" "Cyan"
  Write-ModeCard "3" "重传优先" "适合游戏、语音、远程桌面。" "优先压低重传" "Green"
  Write-BackMenuItem
  $modeChoice = Read-Host "请选择 AI 调参目标 [1-3/0]"
  if (Test-BackChoice $modeChoice) { return $false }
  switch ($modeChoice) {
    "1" { $objective = "startup"; $objectiveName = "快速起速" }
    "2" { $objective = "throughput"; $objectiveName = "吞吐优先" }
    "3" { $objective = "retrans"; $objectiveName = "重传优先" }
    default { Write-Host "无效 AI 调参目标。" -ForegroundColor Yellow; return $false }
  }

  Write-Host ""
  Write-Section "测速"
  $rtt = Get-RttMilliseconds -HostName $HostName
  Write-Note "上传" "本机 -> 对端"
  $upload = Get-IperfMetrics -Result (Run-Iperf -HostName $HostName -Port $Port -LocalAddress $LocalAddress)
  Write-Note "下载" "对端 -> 本机"
  $download = Get-IperfMetrics -Result (Run-Iperf -HostName $HostName -Port $Port -LocalAddress $LocalAddress -Reverse)
  Write-Section "测速摘要"
  Write-MetricLine "上传速度" (Format-Rate $upload.BitsPerSecond) "Cyan"
  Write-MetricLine "上传重传" (Format-Retransmits $upload.Retransmits) (Get-RetransmitsColor $upload.Retransmits)
  Write-MetricLine "下载速度" (Format-Rate $download.BitsPerSecond) "Cyan"
  Write-MetricLine "下载重传" (Format-Retransmits $download.Retransmits) (Get-RetransmitsColor $download.Retransmits)

  Invoke-AgentPost -Url "$PeerUrl/report" -TokenValue $TokenValue -Body ([pscustomobject]@{
    role = "windows-ai-result"
    lan_ip = $LocalAddress
    objective = $objective
    direction = "both"
    retransmits = Add-NullableInt64 -Left $upload.Retransmits -Right $download.Retransmits
    bits_per_second = Max-NullableDouble -Left $upload.BitsPerSecond -Right $download.BitsPerSecond
    upload_bits_per_second = $upload.BitsPerSecond
    upload_retransmits = $upload.Retransmits
    download_bits_per_second = $download.BitsPerSecond
    download_retransmits = $download.Retransmits
    time = [DateTimeOffset]::UtcNow.ToUnixTimeSeconds()
  }) | Out-Null

  $model = Select-AIModel
  $evidence = New-WindowsAIEvidenceV2 -Objective $objective -Upload $upload -Download $download -RttMs $rtt
  $evidenceJson = $evidence | ConvertTo-Json -Depth 8 -Compress
  $prompt = @"
You are the read-only Windows analyst in a conservative TCP tuning controller.
Return exactly one flat JSON object with these fields and no others:
{"schema_version":"2","action":"measure|test_candidate|stop_no_change|stop_complete","diagnosis_class":"controlled enum","confidence_milli":0,"candidate_id":"","measurement_id":"","evidence_ids":"comma_separated_ids","reason_codes":"comma_separated_codes","expected_metric":"throughput|retransmits|first_second|rtt|qdisc_drop|qdisc_backlog|none","expected_direction":"increase|decrease|stable|none","stop_reason":"controlled enum"}
Never return commands or parameter values. Windows is read-only: never claim that a TCP setting was applied.
Evidence: $evidenceJson
"@
  $decision = ConvertFrom-AIDecisionV2 (Invoke-AIChat -Model $model -Prompt $prompt -MaxTokens 512)
  Write-Host ""
  Write-Section "AI 建议摘要"
  Write-MetricLine "模型" $model "Cyan"
  Write-MetricLine "目标" $objectiveName "Cyan"
  Write-MetricLine "建议动作" (Get-WindowsAIV2ActionLabel ([string]$decision.action)) "Yellow"
  Write-MetricLine "诊断类别" (Repair-DisplayText ([string]$decision.diagnosis_class)) "Cyan"
  Write-MetricLine "置信度" ("{0:N1}%" -f ([int64]$decision.confidence_milli / 10.0)) $(if ([int64]$decision.confidence_milli -ge 700) { "Green" } else { "Yellow" })
  Write-MetricLine "预期指标" ("{0} / {1}" -f $decision.expected_metric, $decision.expected_direction) "Cyan"
  Write-MetricLine "理由代码" $(if ($decision.reason_codes) { $decision.reason_codes } else { "未提供" }) "Cyan"
  Write-MetricLine "停止原因" $decision.stop_reason "Cyan"
  Write-MetricLine "修改方式" "Windows 默认不自动写 TCP 栈" "Green"
  if ($decision.action -eq "test_candidate") {
    Write-Note "只读边界" "候选仅供 Linux/OpenWrt 端受控流程参考；Windows 不执行、不写注册表、不调用 netsh。"
  }
  return $true
}

function Invoke-WindowsPresetAssessment {
  param([string]$PeerUrl, [string]$TokenValue, [string]$HostName, [int]$Port, [string]$LocalAddress)
  Write-Header "预制参数评估"
  Write-Subtitle "Windows 端只做测速和推荐，不自动修改 Windows TCP 栈。"
  Write-Host ""
  Write-Section "检测中"
  Write-Note "动作" "正在检测 RTT、iperf3 上传/下载、重传和首秒速度..."

  $rtt = Get-RttMilliseconds -HostName $HostName
  $upload = Get-IperfMetrics -Result (Run-Iperf -HostName $HostName -Port $Port -LocalAddress $LocalAddress)
  $download = Get-IperfMetrics -Result (Run-Iperf -HostName $HostName -Port $Port -LocalAddress $LocalAddress -Reverse)
  $totalRetr = Add-NullableInt64 -Left $upload.Retransmits -Right $download.Retransmits
  $recommended = Select-PresetByProbe -RttMs $rtt -Retransmits $totalRetr -DownloadBitsPerSecond $download.BitsPerSecond

  Invoke-AgentPost -Url "$PeerUrl/report" -TokenValue $TokenValue -Body ([pscustomobject]@{
    role = "windows-preset-assessment"
    lan_ip = $LocalAddress
    stage = "preset-probe"
    result = "ok"
    detail = $recommended.Name
    bits_per_second = Max-NullableDouble -Left $upload.BitsPerSecond -Right $download.BitsPerSecond
    retransmits = $totalRetr
    first_second_bits_per_second = Max-NullableDouble -Left $upload.FirstSecondBitsPerSecond -Right $download.FirstSecondBitsPerSecond
    time = [DateTimeOffset]::UtcNow.ToUnixTimeSeconds()
  }) | Out-Null

  Write-Header "预制参数评估"
  Write-Section "检测结果"
  Write-PanelRow "本机地址" $LocalAddress
  Write-PanelRow "RTT" ("{0}ms" -f $rtt)
  Write-PanelRow "上传" ("{0} / 重传 {1} / 首秒 {2}" -f (Format-Rate $upload.BitsPerSecond), (Format-Retransmits $upload.Retransmits), (Format-Rate $upload.FirstSecondBitsPerSecond))
  Write-PanelRow "下载" ("{0} / 重传 {1} / 首秒 {2}" -f (Format-Rate $download.BitsPerSecond), (Format-Retransmits $download.Retransmits), (Format-Rate $download.FirstSecondBitsPerSecond))
  Write-Host ""
  Write-Section "推荐挡位"
  Write-PanelRow "预设挡位" $recommended.Name
  Write-PanelRow "适用范围" $recommended.Rtt
  Write-PanelRow "接收缓冲" $recommended.Rmem
  Write-PanelRow "发送缓冲" $recommended.Wmem
  Write-Note "说明" $recommended.Comment
  Write-Host ""
  Write-Section "可选挡位"
  foreach ($profile in Get-PresetProfiles) {
    Write-MenuItem $profile.Index $profile.Name ("{0} / 接收 {1} / 发送 {2}" -f $profile.Rtt, $profile.Rmem, $profile.Wmem)
  }
  Write-Host ""
  Write-Note "Windows" "这里只提供评估建议，不自动写入系统 TCP 参数。"
  return $true
}

function Show-AgentEventSummary {
  param([string]$PeerUrl, [string]$TokenValue)
  $data = Invoke-AgentGet -Url "$PeerUrl/events" -TokenValue $TokenValue
  if ($data.summaries -and $data.summaries.Count -gt 0) {
    foreach ($line in $data.summaries) {
      Write-Host "  $line"
    }
    return
  }
  Write-Host "  暂无过程记录。" -ForegroundColor DarkGray
}

function Invoke-RestoreDefaultsMenu {
  param([string]$PeerUrl, [string]$TokenValue)
  Write-Header "恢复默认值"
  Write-Subtitle "Windows 端不自动写入本机 TCP 栈，只请求服务端恢复启动时快照。"
  Write-Host ""
  Write-Section "快照状态"
  Write-PanelRow "本机快照" "不适用"
  if (Test-RemoteDefaultsAvailable -PeerUrl $PeerUrl -TokenValue $TokenValue) {
    Write-PanelRow "服务端快照" "已记录"
  } else {
    Write-PanelRow "服务端快照" "未知或不可用"
  }
  Write-Host ""
  Write-Note "范围" "只恢复服务端首次记录的 TCP/sysctl 快照，不提交任意参数。"
  $answer = Read-Host "确认请求服务端恢复默认值？输入 yes 继续，其他返回"
  if ($answer -ne "yes") { return $false }
  try {
    $result = Invoke-AgentPost -Url "$PeerUrl/restore-defaults" -TokenValue $TokenValue -Body ([pscustomobject]@{})
    if ($result.ok) {
      Write-Host "服务端默认值恢复请求已执行。" -ForegroundColor Green
      return $true
    }
    Write-Host "服务端返回恢复失败。" -ForegroundColor Yellow
    return $false
  } catch {
    Write-Host "服务端默认值恢复请求失败：$($_.Exception.Message)" -ForegroundColor Yellow
    return $false
  }
}

function Show-ClientDashboard {
  param([string]$LocalAddress, [int]$Port)
  Write-Header "TCP 双端调优器 · 客户端"
  Write-Subtitle "Windows 设备已连接，可直接选择优化目标"
  Write-Host ""
  Write-Section "连接状态"
  Write-PanelRow "会话" "已连接"
  Write-PanelRow "本机" "Windows · $LocalAddress"
  Write-PanelRow "测速节点" "已连接的服务端"
  Write-PanelRow "测试端口" "$Port"
  Write-Host ""
  Write-Note "提示" "代理/公网地址仅用于脚本通讯，界面和测试源地址优先使用本机局域网 IP。"
  Write-Note "Windows" "默认只测速和给出建议，不自动修改 Windows TCP 栈。"
}

function Invoke-WindowsOptimization {
  param(
    [string]$PeerUrl,
    [string]$TokenValue,
    [string]$HostName,
    [int]$Port,
    [string]$LocalAddress,
    [string]$SelectedObjective,
    [string]$SelectedDirection,
    [int]$SelectedRounds,
    [int]$SelectedTargetRetr
  )

  $modeName = Get-ObjectiveLabel -Value $SelectedObjective
  $directionName = Get-DirectionLabel -Value $SelectedDirection
  Write-Header "正在评估 · $modeName"
  Write-Subtitle "$directionName · 本机 $LocalAddress · 第 1/$SelectedRounds 轮"
  Write-Host ""
  Write-Section "优化概览"
  Write-PanelRow "模式" $modeName
  Write-PanelRow "测试方向" $directionName
  Write-PanelRow "本机地址" $LocalAddress
  Write-PanelRow "测速节点" "已连接的服务端"
  Write-PanelRow "最大轮数" "$SelectedRounds"
  Write-Host ""
  Write-Note "说明" "Windows 端进行真实链路测试并给出建议，不自动写系统 TCP 参数。"

  $previousRetransmits = $null
  $previousRate = $null
  $firstMetrics = $null
  $bestRate = 0.0
  $lastMetrics = $null
  $completedRounds = 0
  for ($round = 1; $round -le $SelectedRounds; $round++) {
    Write-Host ""
    Write-Section ("第 {0}/{1} 轮测试" -f $round, $SelectedRounds)
    Write-Host "  连接测试 → 分析结果 → 多轮复测 → 生成建议" -ForegroundColor Cyan
    Write-Host ("  轮次 {0}/{1}" -f $round, $SelectedRounds) -ForegroundColor DarkGray
    Write-Note "状态" "正在用 iperf3 测试真实链路..."
    $result = Run-Iperf -HostName $HostName -Port $Port -LocalAddress $LocalAddress -Reverse:($SelectedDirection -eq "download")
    $metrics = Get-IperfMetrics -Result $result
    $lastMetrics = $metrics
    $completedRounds = $round
    if (-not $firstMetrics) { $firstMetrics = $metrics }
    if ($metrics.BitsPerSecond -gt $bestRate) { $bestRate = $metrics.BitsPerSecond }

    $prevRateText = if ($null -eq $previousRate) { "无" } else { Format-Rate $previousRate }
    $prevRetrText = if ($null -eq $previousRetransmits) { "无" } else { "{0:N0} 次" -f $previousRetransmits }
    $trend = Get-TrendLabel -Current $metrics.Retransmits -Previous $previousRetransmits
    $delta = Get-PercentDelta -Before $firstMetrics.Retransmits -After $metrics.Retransmits
    $action = Get-NextActionLabel -ObjectiveValue $SelectedObjective -Retransmits $metrics.Retransmits -TargetRetransmits $SelectedTargetRetr
    $trendColor = if ($trend -eq "重传上升") { "Yellow" } else { "Green" }
    Write-MetricLine "当前速度" ("{0}（上轮 {1}）" -f (Format-Rate $metrics.BitsPerSecond), $prevRateText) "Cyan"
    $currentRetrText = Format-Retransmits $metrics.Retransmits
    $currentRetrColor = if ($null -eq $metrics.Retransmits) { "DarkGray" } elseif (Test-RetransmitsAtOrBelowTarget $metrics.Retransmits $SelectedTargetRetr) { "Green" } else { "Red" }
    Write-MetricLine "当前重传" ("{0}（上轮 {1}）" -f $currentRetrText, $prevRetrText) $currentRetrColor
    Write-MetricLine "改善幅度" ("{0} · {1}" -f $delta, $trend) $trendColor
    Write-MetricLine "当前动作" $action "Yellow"
    if ($SelectedObjective -eq "startup") {
      Write-MetricLine "首秒速度" (Format-Rate $metrics.FirstSecondBitsPerSecond) "Yellow"
    }

    Invoke-AgentPost -Url "$PeerUrl/report" -TokenValue $TokenValue -Body ([pscustomobject]@{
      role = "windows-client"
      lan_ip = $LocalAddress
      round = $round
      retransmits = $metrics.Retransmits
      bits_per_second = $metrics.BitsPerSecond
      first_second_bits_per_second = $metrics.FirstSecondBitsPerSecond
      objective = $SelectedObjective
      direction = $SelectedDirection
      time = [DateTimeOffset]::UtcNow.ToUnixTimeSeconds()
    }) | Out-Null

    if ($SelectedObjective -eq "retrans" -and (Test-RetransmitsAtOrBelowTarget $metrics.Retransmits $SelectedTargetRetr)) {
      Write-Host ""
      Write-Host ("目标已达成：重传降至 {0:N0} 次。" -f $metrics.Retransmits) -ForegroundColor Green
      break
    }
    $previousRetransmits = $metrics.Retransmits
    $previousRate = $metrics.BitsPerSecond
  }

  if ($completedRounds -le 0) { $completedRounds = $SelectedRounds }
  Write-Header "链路评估完成"
  Write-Subtitle "$modeName · $directionName · 共测试 $completedRounds 轮"
  Write-Host ""
  Write-Section "结论"
  if (-not $lastMetrics) { return }
  $firstRateText = Format-Rate $firstMetrics.BitsPerSecond
  $lastRateText = Format-Rate $lastMetrics.BitsPerSecond
  $speedDelta = Get-PercentDelta -Before $firstMetrics.BitsPerSecond -After $lastMetrics.BitsPerSecond
  $retrDelta = Get-PercentDelta -Before $firstMetrics.Retransmits -After $lastMetrics.Retransmits
  if ($SelectedObjective -eq "throughput") {
    Write-PanelRow "结论" ("测试完成：最高速度 {0}。" -f (Format-Rate $bestRate))
  } elseif ($SelectedObjective -eq "startup") {
    Write-PanelRow "结论" ("测试完成：末轮首秒速度 {0}。" -f (Format-Rate $lastMetrics.FirstSecondBitsPerSecond))
  } elseif ($null -eq $lastMetrics.Retransmits) {
    Write-PanelRow "结论" "未检测到重传指标，不能判断是否达到目标。"
  } elseif ($lastMetrics.Retransmits -gt $SelectedTargetRetr) {
    Write-PanelRow "结论" "重传尚未达到目标，建议先检查 Wi-Fi、网线、代理链路或拥塞。"
  } else {
    Write-PanelRow "结论" ("目标已达成：重传降至 {0:N0} 次。" -f $lastMetrics.Retransmits)
  }
  Write-Host ""
  Write-Section "首轮与末轮对比"
  $hdrLabel = Format-Pad -Text "指标" -Width 12
  Write-Host ("  $hdrLabel │ {0,-14} │ {1,-14} │ {2,-10}" -f "优化前", "优化后", "变化") -ForegroundColor Cyan
  Write-Host ("  {0}" -f ("─" * 57)) -ForegroundColor DarkGray
  $lbl1 = Format-Pad -Text "传输速度" -Width 12
  Write-Host ("  $lbl1 │ {0,-14} │ {1,-14} │ {2,-10}" -f $firstRateText, $lastRateText, $speedDelta)
  $lbl2 = Format-Pad -Text "重传次数" -Width 12
  Write-Host ("  $lbl2 │ {0,-14} │ {1,-14} │ {2,-10}" -f (Format-Retransmits $firstMetrics.Retransmits), (Format-Retransmits $lastMetrics.Retransmits), $retrDelta)
  if ($SelectedObjective -eq "startup") {
    $startupDelta = Get-PercentDelta -Before $firstMetrics.FirstSecondBitsPerSecond -After $lastMetrics.FirstSecondBitsPerSecond
    $firstStartupText = Format-Rate $firstMetrics.FirstSecondBitsPerSecond
    $lastStartupText = Format-Rate $lastMetrics.FirstSecondBitsPerSecond
    $lbl3 = Format-Pad -Text "首秒速度" -Width 12
    Write-Host ("  $lbl3 │ {0,-14} │ {1,-14} │ {2,-10}" -f $firstStartupText, $lastStartupText, $startupDelta)
  }
  Write-Host ""
  Write-Section "配置摘要"
  Write-Note "Windows" "未自动修改 TCP 栈；以上为真实链路测试结果和优化建议。"
  Write-Host ""
  Write-Section "下一步操作"
  Write-MenuItem "1" "返回客户端主页" "回到操作菜单"
  Write-MenuItem "2" "换一种模式继续" "重新选择优化目标"
  Write-MenuItem "3" "查看详细参数" "检查当前 TCP 配置"
  Write-MenuItem "4" "无需回滚" "Windows 端未修改系统 TCP 栈" "DarkGray"
}

function Select-WindowsOptimization {
  param([string]$PeerUrl, [string]$TokenValue, [string]$HostName, [int]$Port, [string]$LocalAddress)
  Write-Header "选择优化目标"
  Write-Subtitle "先选目标，再选测试方向。所有修改都可以回滚。"
  Write-Host ""
  Write-Section "优化模式"
  Write-ModeCard "1" "重传优先" "适合游戏、语音、远程桌面。" "尽量把重传降到 0" "Green"
  Write-ModeCard "2" "吞吐优先" "适合下载、备份、大文件。" "优先提升稳定传输速率" "Cyan"
  Write-ModeCard "3" "快速起速" "适合网页、短连接、小文件。" "缩短连接初期的提速时间" "Yellow"
  Write-BackMenuItem
  $modeChoice = Read-Host "请选择优化目标 [1-3/0]"
  if (Test-BackChoice $modeChoice) { return $false }
  switch ($modeChoice) {
    "1" { $selectedObjective = "retrans"; $selectedRounds = 5; $selectedTarget = 0 }
    "2" { $selectedObjective = "throughput"; $selectedRounds = 3; $selectedTarget = 10 }
    "3" { $selectedObjective = "startup"; $selectedRounds = 3; $selectedTarget = 5 }
    default { Write-Host "无效优化目标。" -ForegroundColor Yellow; return $false }
  }

  Write-Host ""
  Write-Section "测试方向"
  Write-Host "  [1] 下载  服务端 -> 本机"
  Write-Host "  [2] 上传  本机 -> 服务端"
  Write-BackMenuItem
  Write-Host "当前选择：" -NoNewline -ForegroundColor Green
  Write-Host ("{0} · 默认下载方向" -f (Get-ObjectiveLabel -Value $selectedObjective))
  $directionChoice = Read-Host "请选择测试方向 [1-2/0]"
  if (Test-BackChoice $directionChoice) { return $false }
  switch ($directionChoice) {
    "1" { $selectedDirection = "download" }
    "2" { $selectedDirection = "upload" }
    default { Write-Host "无效测试方向。" -ForegroundColor Yellow; return $false }
  }
  Invoke-WindowsOptimization -PeerUrl $PeerUrl -TokenValue $TokenValue -HostName $HostName -Port $Port -LocalAddress $LocalAddress -SelectedObjective $selectedObjective -SelectedDirection $selectedDirection -SelectedRounds $selectedRounds -SelectedTargetRetr $selectedTarget
  return $true
}

function Invoke-ClientMenu {
  param([string]$PeerUrl, [string]$TokenValue, [string]$HostName, [int]$Port, [string]$LocalAddress)
  while ($true) {
    Show-ClientDashboard -LocalAddress $LocalAddress -Port $Port
    Write-Host ""
    Write-Section "操作菜单"
    Write-MenuGroup "优化"
    Write-MenuItem "0" "预制参数评估" "先检测双端基础信息，再推荐五档参数" "Yellow"
    Write-MenuItem "1" "稳定自动优化" "不用 AI，规则固定，自动测速迭代" "Green"
    Write-MenuItem "2" "AI 智能优化" "AI 给建议，脚本按白名单执行" "Cyan"
    Write-Host ""
    Write-MenuGroup "状态"
    Write-MenuItem "3" "查看本机状态" "系统 / TCP 参数"
    Write-MenuItem "4" "查看服务端状态" "会话 / 测速服务"
    Write-MenuItem "5" "查看过程记录" "中文摘要日志"
    Write-Host ""
    Write-MenuGroup "测速"
    Write-MenuItem "8" "iperf3 速度测试" "简单测速，不修改参数" "Cyan"
    Write-Host ""
    Write-MenuGroup "退出"
    Write-MenuItem "6" "回滚最近修改" "Windows 端不自动写入，仅提示说明" "Yellow"
    Write-MenuItem "9" "恢复默认值" (Get-DefaultsMenuTag -PeerUrl $PeerUrl -TokenValue $TokenValue) "Yellow"
    Write-MenuItem "7" "停止会话并退出" "清理 Agent / iperf3" "Yellow"
    Write-MenuItem "q" "退出客户端" "不停止服务端会话" "DarkGray"
    $choice = Read-Host "请选择"
    switch ($choice) {
      "0" { if (Invoke-WindowsPresetAssessment -PeerUrl $PeerUrl -TokenValue $TokenValue -HostName $HostName -Port $Port -LocalAddress $LocalAddress) { Read-Host "按回车返回主菜单" | Out-Null } }
      "1" { if (Select-WindowsOptimization -PeerUrl $PeerUrl -TokenValue $TokenValue -HostName $HostName -Port $Port -LocalAddress $LocalAddress) { Read-Host "按回车返回主菜单" | Out-Null } }
      "2" { if (Invoke-WindowsAITuning -PeerUrl $PeerUrl -TokenValue $TokenValue -HostName $HostName -Port $Port -LocalAddress $LocalAddress) { Read-Host "按回车返回主菜单" | Out-Null } }
      "3" { & $PSCommandPath status; Read-Host "按回车返回主菜单" | Out-Null }
      "4" { Invoke-AgentGet -Url "$PeerUrl/status" -TokenValue $TokenValue | ConvertTo-Json -Depth 8; Read-Host "按回车返回主菜单" | Out-Null }
      "5" { Show-AgentEventSummary -PeerUrl $PeerUrl -TokenValue $TokenValue; Read-Host "按回车返回主菜单" | Out-Null }
      "6" { Write-Host "Windows 端默认没有自动写入 TCP 参数，无需回滚。" -ForegroundColor Yellow; Read-Host "按回车返回主菜单" | Out-Null }
      "7" { Invoke-AgentPost -Url "$PeerUrl/stop" -TokenValue $TokenValue -Body ([pscustomobject]@{}) | Out-Null; return }
      "8" { Invoke-Iperf3Speedtest -HostName $HostName -Port $Port; Read-Host "按回车返回主菜单" | Out-Null }
      "9" { Invoke-RestoreDefaultsMenu -PeerUrl $PeerUrl -TokenValue $TokenValue | Out-Null; Read-Host "按回车返回主菜单" | Out-Null }
      "q" { return }
      "Q" { return }
      default { Write-Host "无效选择。" -ForegroundColor Yellow }
    }
  }
}

function Invoke-TcpTuneMain {
if ($Rounds -lt 1 -or $Rounds -gt 10) { throw "Rounds 必须在 1 到 10 之间。" }
if ($TargetRetr -lt 0 -or $TargetRetr -gt 1000000) { throw "TargetRetr 超出允许范围。" }
if ($IperfPort -lt 1 -or $IperfPort -gt 65535) { throw "IperfPort 必须在 1 到 65535 之间。" }
if ($Command -eq "status") {
  $cachedIperf = Get-CachedIperf3
  $statusData = [pscustomobject]@{
    App = "TCP 双端调优器 Windows 客户端"
    Version = $AppVersion
    Repo = $RepoUrl
    OS = [System.Environment]::OSVersion.VersionString
    Architecture = $env:PROCESSOR_ARCHITECTURE
    LanIPv4 = Get-LocalLanIPv4
    LanIPv6 = Get-LocalLanIPv6
    HasIperf3 = [bool]((Get-Command iperf3 -ErrorAction SilentlyContinue) -or $cachedIperf)
    CachedIperf3 = $cachedIperf
    HasWinget = [bool](Get-Command winget -ErrorAction SilentlyContinue)
    HasChoco = [bool](Get-Command choco -ErrorAction SilentlyContinue)
    HasScoop = [bool](Get-Command scoop -ErrorAction SilentlyContinue)
  }
  if ($Json) {
    [pscustomobject]@{ schema_version = 1; ok = $true; command = "status"; data = $statusData; errors = @() } | ConvertTo-Json -Depth 6
  } else {
    $statusData | ConvertTo-Json -Depth 4
  }
  return
}

if ($Command -eq "join" -or $Command -eq "client") {
  if (-not $Peer) { throw "$Command 需要 -Peer http://IP:PORT" }
  if (-not $Token) { throw "$Command 需要 -Token" }
  Test-PeerUri -Url $Peer | Out-Null
  Ensure-Command -Name "iperf3"

  $hostName = Get-PeerHost -Url $Peer
  $localAddress = Get-LocalBindAddress -HostName $hostName
  $report = [pscustomobject]@{
    role = "windows-client"
    os = [System.Environment]::OSVersion.VersionString
    architecture = $env:PROCESSOR_ARCHITECTURE
    lan_ip = $localAddress
    objective = $Objective
    target_retr = $TargetRetr
    time = [DateTimeOffset]::UtcNow.ToUnixTimeSeconds()
  }
  Invoke-AgentPost -Url "$Peer/report" -TokenValue $Token -Body $report | Out-Null

  if ($Command -eq "client") {
    Write-Host "已连接到服务端会话。" -ForegroundColor Green
    if (-not $script:IsNonInteractive) {
      Invoke-ClientMenu -PeerUrl $Peer -TokenValue $Token -HostName $hostName -Port $IperfPort -LocalAddress $localAddress
    }
    return
  }

  Invoke-WindowsOptimization -PeerUrl $Peer -TokenValue $Token -HostName $hostName -Port $IperfPort -LocalAddress $localAddress -SelectedObjective $Objective -SelectedDirection $Direction -SelectedRounds $Rounds -SelectedTargetRetr $TargetRetr
}
}

try {
  Invoke-TcpTuneMain
} catch {
  $message = $_.Exception.Message
  $code = $ExitNetwork
  if ($message -match 'token|auth|401|403') { $code = $ExitAuthentication }
  elseif ($message -match 'iperf3.*(测试|JSON|速率|超时)|测速') { $code = $ExitBenchmark }
  elseif ($message -match '^AI |AI 返回|AI 请求|AI 网关|模型') { $code = $ExitAi }
  elseif ($message -match '缺少命令|安装|SHA256|压缩包|版本验证') { $code = $ExitDependency }
  elseif ($message -match '必须|无效|超出|不允许|格式') { $code = $ExitArguments }
  if ($Json) {
    [pscustomobject]@{ schema_version = 1; ok = $false; command = $Command; data = $null; errors = @([pscustomobject]@{ code = $code; message = $message }) } | ConvertTo-Json -Depth 6
  } else {
    [Console]::Error.WriteLine($message)
  }
  exit $code
}
