# Module: src/core/exit-codes.sh
EXIT_OK=0
EXIT_USAGE=2
EXIT_DEPENDENCY=3
EXIT_NETWORK=4
EXIT_AUTH=5
EXIT_BENCHMARK=6
EXIT_APPLY=7
EXIT_AI=8
EXIT_INTERRUPTED=130
export EXIT_OK EXIT_USAGE EXIT_DEPENDENCY EXIT_NETWORK EXIT_AUTH EXIT_BENCHMARK EXIT_APPLY EXIT_AI EXIT_INTERRUPTED
