param([switch]$Check)

$ErrorActionPreference = "Stop"
$repoRoot = Split-Path -Parent $PSScriptRoot
# Nested Join-Path keeps the separator portable between Windows PowerShell 5.1 and Linux pwsh.
$sourceRoot = Join-Path (Join-Path $repoRoot "src") "windows"
$target = Join-Path $repoRoot "tcp-tune.ps1"
$modules = @(
  "00-entry.ps1",
  "10-ui.ps1",
  "20-runtime.ps1",
  "30-network.ps1",
  "50-cli.ps1"
)
$utf8 = [Text.UTF8Encoding]::new($false)
$utf8Bom = [Text.UTF8Encoding]::new($true)
$parts = [Collections.Generic.List[string]]::new()
foreach ($module in $modules) {
  $path = Join-Path $sourceRoot $module
  if (-not (Test-Path -LiteralPath $path -PathType Leaf)) { throw "Missing PowerShell module: $module" }
  $content = [IO.File]::ReadAllText($path, $utf8).TrimEnd("`r", "`n")
  $parts.Add($content)
}
$generated = "# AUTO-GENERATED by scripts/build-powershell.ps1; edit src/windows instead.`n" + (($parts -join "`n`n").Replace("`r`n", "`n")) + "`n"

if ($Check) {
  if (-not (Test-Path -LiteralPath $target)) { throw "Missing generated file: tcp-tune.ps1" }
  $actual = [IO.File]::ReadAllText($target, $utf8).Replace("`r`n", "`n")
  if ($actual -cne $generated) { throw "tcp-tune.ps1 differs from src/windows; run scripts/build-powershell.ps1." }
  Write-Output "tcp-tune.ps1 generated file is up to date."
  exit 0
}

[IO.File]::WriteAllText($target, $generated, $utf8Bom)
Write-Output "Generated tcp-tune.ps1 from $($modules.Count) modules."
