#!/bin/sh
set -eu

ROOT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
MANIFEST="$ROOT_DIR/scripts/shell-modules.txt"
OUTPUT="$ROOT_DIR/tcp-tune.sh"
TMP="${TMPDIR:-/tmp}/tcp-tune-build-$$"
trap 'rm -f "$TMP"' EXIT HUP INT TERM

{
  printf '%s\n' '#!/bin/sh'
  printf '%s\n' '# Generated from src/ by scripts/build-shell.sh. Do not edit this file directly.'
} > "$TMP"
while IFS= read -r module || [ -n "$module" ]; do
  case "$module" in ''|'#'*) continue ;; esac
  [ -f "$ROOT_DIR/$module" ] || {
    printf '缺少 Shell 模块：%s\n' "$module" >&2
    exit 1
  }
  printf '\n# BEGIN %s\n' "$module" >> "$TMP"
  if [ "$module" = "src/agent/lifecycle.sh" ]; then
    while IFS= read -r line || [ -n "$line" ]; do
      if [ "$line" = "@@TCP_TUNE_AGENT_SOURCE@@" ]; then
        sed 's/\r$//' "$ROOT_DIR/src/agent/http_agent.py" >> "$TMP"
      else
        printf '%s\n' "$line" >> "$TMP"
      fi
    done < "$ROOT_DIR/$module"
  else
    sed 's/\r$//' "$ROOT_DIR/$module" >> "$TMP"
  fi
  printf '\n# END %s\n' "$module" >> "$TMP"
done < "$MANIFEST"

if [ "${1:-}" = "--check" ]; then
  cmp -s "$TMP" "$OUTPUT" || {
    printf 'tcp-tune.sh 与 src 模块不一致，请运行 scripts/build-shell.sh。\n' >&2
    exit 1
  }
  exit 0
fi

if ! cmp -s "$TMP" "$OUTPUT" 2>/dev/null; then
  cp "$TMP" "$OUTPUT"
  chmod +x "$OUTPUT" 2>/dev/null || true
fi
